import { SizeConfig } from '@/lib/doodle/types'

export const sizeConfig: Record<'sm' | 'md' | 'lg' | 'xl', SizeConfig> = {
  sm: {
    text: 'text-xl',
    eyeOuter: 'w-5 h-5',
    eyeMiddle: 'w-3.5 h-3.5',
    eyeInner: 'w-2 h-2',
    coreSize: 'w-1 h-1',
    arcWidth: '2px',
    glowSize: '4px',
    eyeOuterPx: 20,
    eyeMiddlePx: 14,
    eyeInnerPx: 8,
    maxOffset: 2,
  },
  md: {
    text: 'text-2xl',
    eyeOuter: 'w-6 h-6',
    eyeMiddle: 'w-4 h-4',
    eyeInner: 'w-2.5 h-2.5',
    coreSize: 'w-1.5 h-1.5',
    arcWidth: '2px',
    glowSize: '6px',
    eyeOuterPx: 24,
    eyeMiddlePx: 16,
    eyeInnerPx: 10,
    maxOffset: 3,
  },
  lg: {
    text: 'text-4xl',
    eyeOuter: 'w-9 h-9',
    eyeMiddle: 'w-6 h-6',
    eyeInner: 'w-3.5 h-3.5',
    coreSize: 'w-2 h-2',
    arcWidth: '3px',
    glowSize: '8px',
    eyeOuterPx: 36,
    eyeMiddlePx: 24,
    eyeInnerPx: 14,
    maxOffset: 4,
  },
  xl: {
    text: 'text-6xl',
    eyeOuter: 'w-14 h-14',
    eyeMiddle: 'w-9 h-9',
    eyeInner: 'w-5 h-5',
    coreSize: 'w-3 h-3',
    arcWidth: '4px',
    glowSize: '12px',
    eyeOuterPx: 56,
    eyeMiddlePx: 36,
    eyeInnerPx: 20,
    maxOffset: 6,
  },
}
